version: '3'

services:
  gateway:
    container_name: gateway
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${GATEWAY_PORT:-8800}:80'
    restart: always
    depends_on:
      auth:
        condition: service_started
      private:
        condition: service_started

  auth:
    build: .
    image: demo_auth_request
    command: ['node', 'src/auth.js']

  private:
    image: demo_auth_request
    command: ['node', 'src/private.js']
