efk-up:
	docker-compose -p efk -f docker-compose.efk.yml up -d

efk-down:
	docker-compose -p efk -f docker-compose.efk.yml down

efk-down-v:
	docker-compose -p efk -f docker-compose.efk.yml down -v

run:
	go run main.go

up:
	docker-compose -p demo-app-logging up -d

down:
	docker-compose -p demo-app-logging down